# Generated by Django 5.0.1 on 2026-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
