"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
from re import DEBUG
from decouple import Config, RepositoryEnv, UndefinedValueError
from django.core.exceptions import ImproperlyConfigured
import os

# --------------------------------------------------
# BASE DIR & ENV
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / ".env"
config = Config(RepositoryEnv(env_path))

# --------------------------------------------------
# SECURITY
# --------------------------------------------------

# Fail closed: a missing/misconfigured .env must stop the app from starting,
# not silently fall back to a publicly-known secret key. Previously defaulted
# to "django-insecure-change-this-in-production", which would have shipped
# to production undetected on a broken .env.
try:
    SECRET_KEY = config("SECRET_KEY")
except UndefinedValueError:
    raise ImproperlyConfigured(
        "SECRET_KEY is not set in .env — refusing to start with an "
        "insecure default. Set SECRET_KEY in the .env file."
    )

# Fail closed: DEBUG defaults to False, not True — a deploy that forgets to
# set DEBUG in .env must not accidentally serve debug pages/stack traces.
#DEBUG = config("DEBUG", default=True, cast=bool)

DEBUG = True

# FIX: Hardcoded ALLOWED_HOSTS — no https://, no spaces issues, no .env parsing problems
ALLOWED_HOSTS = [
    "miuedu.com",
    "www.miuedu.com",
    "127.0.0.1",
    "localhost",
    "mail.miuedu.com",
    "10.191.120.12",
    "*"
]


CSRF_TRUSTED_ORIGINS = [
    "http://10.191.120.12:8000",
]

# --------------------------------------------------
# APPLICATION DEFINITION
# --------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Project apps
    "apps.eduweb",
    "apps.management",
    "apps.student",
    "apps.parent",
    "apps.instructor",
    "apps.finance",
    "apps.payments",
    "apps.melbac",
    'apps.library',
    'apps.store',

    "django.contrib.humanize",
    'apps.chatbot',
    'apps.support',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.eduweb.security_middleware.SessionSecurityMiddleware",
    "apps.eduweb.exam_middleware.ExamLockMiddleware",
    "apps.store.middleware.StoreCustomerScopeMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.eduweb.views.application_status_context",
                "apps.eduweb.context.navigation_data",
                'apps.eduweb.context.site_config_context',
                "apps.eduweb.context.student_counts",
                'apps.eduweb.context.admin_counts',
                'apps.eduweb.context.instructor_counts',
                'apps.eduweb.context.permissions_context',
                'apps.support.context_processors.support_context',
                'apps.store.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# --------------------------------------------------
# DATABASE
# --------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": config("DB_NAME"),
#         "USER": config("DB_USER"),
#         "PASSWORD": config("DB_PASSWORD"),
#         "HOST": config("DB_HOST", default="localhost"),
#         "PORT": config("DB_PORT", default="5432", cast=str),
#     }
# }

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": config("DB_NAME"),
#         "USER": config("DB_USER"),
#         "PASSWORD": config("DB_PASSWORD"),
#         "HOST": config("DB_HOST", default="localhost"),
#         "PORT": config("DB_PORT", default="3306"),
#         "OPTIONS": {
#             "charset": "utf8mb4",
#             "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------

LANGUAGE_CODE = "en-ng"
TIME_ZONE = "Africa/Lagos"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# STATIC & MEDIA
# --------------------------------------------------

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
FILE_UPLOAD_PERMISSIONS = 0o644

# --------------------------------------------------
# DEFAULT PRIMARY KEY
# --------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------------------------------------
# EMAIL CONFIGURATION
# --------------------------------------------------

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=465, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="Abraytech <noreply@abraytech.com>")
CONTACT_EMAIL = config("CONTACT_EMAIL", default="admin@abraytech.com")
# All emails in this app are sent synchronously in the request path (a prior
# attempt to background them via daemon threads caused emails to silently
# never send in production — Passenger/shared-hosting can recycle the worker
# process before a detached thread finishes). 120s meant a slow/unresponsive
# SMTP server could hold an interactive request (login OTP, signup, etc.)
# open for two full minutes before failing — indistinguishable from a hang.
# 15s is long enough for a normal send (observed 1-5s in practice) while
# bounding the worst case to something a user will actually wait out.
EMAIL_TIMEOUT = 15

# --------------------------------------------------
# AUTH & SESSION
# --------------------------------------------------

LOGIN_URL = "/auth/"
LOGIN_REDIRECT_URL = "eduweb:apply"
LOGOUT_REDIRECT_URL = "eduweb:index"

SESSION_COOKIE_AGE = 1209600
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # per-login set_expiry(0) handles browser-close
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

SESSION_ENGINE = "django.contrib.sessions.backends.db"
CSRF_COOKIE_HTTPONLY = False

# --------------------------------------------------
# SECURITY FLAGS (PRODUCTION)
# --------------------------------------------------

SECURE_SSL_REDIRECT = config(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=False,
    cast=bool,
)

CSRF_COOKIE_SECURE = config(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=False,
    cast=bool,
)

# --------------------------------------------------
# STRIPE PAYMENT SETTINGS
# --------------------------------------------------

STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLIC_KEY = config("STRIPE_PUBLIC_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

# --------------------------------------------------
# PAYSTACK PAYMENT SETTINGS (store checkout only — Stripe above stays the
# application/course-fee gateway)
# --------------------------------------------------

PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY", default="")
PAYSTACK_PUBLIC_KEY = config("PAYSTACK_PUBLIC_KEY", default="")

# --------------------------------------------------
# CORS / CSRF
# --------------------------------------------------

# FIX: Hardcoded trusted origins with proper https:// format
# CSRF_TRUSTED_ORIGINS = [
#     "https://miuedu.com",
#     "https://www.miuedu.com",
#     "http://127.0.0.1",
#     "http://localhost",
# ]

CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS

# settings.py
CHAT_SESSION_TIMEOUT_MINUTES = 15

# ── Inactivity session timeout ────────────────────────────────────────────────
# Minutes of no requests before SessionSecurityMiddleware kills the session.
# Change this single value to adjust the timeout across the whole platform.
SESSION_INACTIVITY_TIMEOUT = 15  # minutes