# Generated by Django 6.0.3 on 2026-05-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=200)),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dashboard_images/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Brief description of this dashboard screen')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (ascending)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('project', 'order')},
            },
        ),
    ]
