# Generated by Django 6.0.2 on 2026-03-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='email_admissions',
            field=models.EmailField(blank=True, help_text='Admissions department email — contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_info',
            field=models.EmailField(blank=True, help_text='General info email — contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_international',
            field=models.EmailField(blank=True, help_text='International enquiries email — contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='office_hours_saturday',
            field=models.CharField(blank=True, default='Saturday: 9:00 AM - 1:00 PM', help_text="Saturday office hours e.g. 'Saturday: 9:00 AM - 1:00 PM'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='office_hours_sunday',
            field=models.CharField(blank=True, default='Sunday: Closed', help_text="Sunday office hours e.g. 'Sunday: Closed'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='office_hours_weekday',
            field=models.CharField(blank=True, default='Monday - Friday: 8:00 AM - 6:00 PM', help_text="Weekday office hours e.g. 'Monday - Friday: 8:00 AM - 6:00 PM'", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='phone_admissions',
            field=models.CharField(blank=True, help_text="Admissions phone line — contact page e.g. '+1 (555) 123-4567'", max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='phone_general',
            field=models.CharField(blank=True, help_text='General enquiries phone line — contact page', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='phone_international',
            field=models.CharField(blank=True, help_text='International office phone line — contact page', max_length=30),
        ),
    ]
