# Generated by Django 6.0.2 on 2026-03-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_siteconfig_email_admissions_siteconfig_email_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_mission',
            field=models.TextField(blank=True, default='To provide accessible, innovative, and transformative education that empowers individuals from all backgrounds to achieve their full potential and make meaningful contributions to society.', help_text='Our Mission text — about page Mission card'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_values',
            field=models.JSONField(blank=True, default=list, help_text='List of core values shown in the Values card. Store as a JSON array of strings, e.g. ["Excellence in Education", "Diversity & Inclusion", "Innovation & Creativity", "Global Citizenship"]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_vision',
            field=models.TextField(blank=True, default='To be a globally recognized leader in higher education, known for innovation, inclusivity, and preparing future-ready graduates who drive positive change worldwide.', help_text='Our Vision text — about page Vision card'),
        ),
        migrations.CreateModel(
            name='SiteHistoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='e.g. 1995')),
                ('title', models.CharField(help_text="e.g. 'Founding' — displayed as '1995 – Founding'", max_length=150)),
                ('description', models.TextField(help_text='One or two sentences describing what happened that year')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first. Leave 0 to sort by year instead.')),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_milestones', to='eduweb.siteconfig')),
            ],
            options={
                'verbose_name': 'History Milestone',
                'verbose_name_plural': 'History Milestones',
                'ordering': ['display_order', 'year'],
            },
        ),
    ]
