# Generated by Django 6.0.2 on 2026-03-24 01:39

import django.core.validators
import django.db.models.deletion
import apps.eduweb.models as eduweb_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0003_alter_feepayment_options_siteconfig_about_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Periodicals', 'Periodicals'), ('References', 'References'), ('Other', 'Other')], db_index=True, default='Books', help_text='Top-level section: Books | Periodicals | References | Other', max_length=50)),
                ('subcategory', models.CharField(db_index=True, help_text="Sub-section label exactly as shown on the front-end, e.g. 'Apologetics Books', 'Dictionaries', 'Acta Theologica', 'Commentaries' …", max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, help_text='Author / Editor full name', max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Year of publication', null=True)),
                ('edition', models.CharField(blank=True, help_text="e.g. 'Vol. 2', '3rd Edition'", max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=30, verbose_name='ISBN / ISSN')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español (Spanish)'), ('fr', 'Français (French)'), ('pt_br', 'Português (Brazil)'), ('ja', '日本語 (Japanese)'), ('zh', '简体中文 (Chinese Simplified)'), ('ko', '한국어 (Korean)'), ('ur', 'اردو (Urdu)'), ('ar', 'العربية (Arabic)'), ('hi', 'हिन्दी (Hindi)'), ('other', 'Other')], default='en', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Abstract, synopsis, or table of contents')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=500)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional thumbnail shown on library cards', null=True, upload_to=eduweb_models.library_cover_upload_path)),
                ('file', models.FileField(blank=True, help_text='Upload PDF, DOCX, EPUB, TXT, PPTX or XLSX', null=True, upload_to=eduweb_models.library_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'epub', 'txt', 'pptx', 'xlsx'])])),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-filled on save', max_digits=8, null=True)),
                ('file_type', models.CharField(blank=True, editable=False, help_text='Auto-detected extension: pdf, docx …', max_length=10)),
                ('external_url', models.URLField(blank=True, help_text='Paste a URL if the document is hosted externally (Google Drive, Project Gutenberg, archive.org, etc.)', max_length=1000)),
                ('external_url_label', models.CharField(blank=True, default='Read / Download', help_text='Front-end button label for the external link', max_length=100)),
                ('allow_download', models.BooleanField(default=True, help_text='Show a Download button on the front-end')),
                ('allow_read_online', models.BooleanField(default=True, help_text='Show an embedded PDF viewer (Read Online) on the front-end')),
                ('access', models.CharField(choices=[('public', 'Public – anyone can access'), ('members', 'Members only – must be logged in')], default='public', help_text='Who can see and open this item', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('featured', models.BooleanField(default=False, help_text='Pin this item to the library home / featured shelf')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the sub-category (lower number = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Item',
                'verbose_name_plural': 'Library Items',
                'ordering': ['category', 'subcategory', 'order', 'title'],
                'indexes': [models.Index(fields=['category', 'subcategory'], name='eduweb_libr_categor_f498d0_idx'), models.Index(fields=['access', 'is_active'], name='eduweb_libr_access_5df669_idx'), models.Index(fields=['featured'], name='eduweb_libr_feature_be3ad3_idx'), models.Index(fields=['slug'], name='eduweb_libr_slug_f6e875_idx')],
            },
        ),
    ]
