# Generated by Django 6.0.2 on 2026-03-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_libraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full institution name', max_length=300)),
                ('category', models.CharField(choices=[('partner', 'Partner'), ('affiliation', 'Affiliation'), ('accreditation', 'Accreditation')], default='partner', max_length=20)),
                ('location', models.CharField(blank=True, help_text="e.g. 'New Jersey, USA'", max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Partner logo image (PNG/SVG recommended, transparent background)', null=True, upload_to='partners/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
            ],
            options={
                'verbose_name': 'Institution Partner / Affiliation',
                'verbose_name_plural': 'Institution Partners & Affiliations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
