# Generated by Django 6.0.2 on 2026-03-28 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0005_institutionpartner_userprofile_password_reset_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('lms_course', 'LMS Course'), ('program', 'Academic Program')], default='lms_course', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='FeePayment.payment_reference that settled this certificate fee', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text="Certificate is only downloadable once payment_status is 'paid'", max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_certificates', to='eduweb.program'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='graduated_at',
            field=models.DateField(blank=True, help_text='Date graduation was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='graduated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduations_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='is_graduated',
            field=models.BooleanField(default=False, help_text='Student has completed all program requirements and graduated'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='transcript_issued',
            field=models.BooleanField(default=False, help_text='Transcript has been generated and made available to the student'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='transcript_issued_at',
            field=models.DateTimeField(blank=True, help_text='When the transcript was issued', null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='transcript_requested',
            field=models.BooleanField(default=False, help_text='Student has formally requested their academic transcript'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='eduweb.lmscourse'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student', 'certificate_type'], name='eduweb_cert_student_ab6de8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['payment_status'], name='eduweb_cert_payment_49cfef_idx'),
        ),
    ]
