# Generated by Django 6.0.2 on 2026-03-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_alter_certificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_session_key',
            field=models.CharField(blank=True, default='', help_text='Django session key of the current active session.', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_logged_in',
            field=models.BooleanField(default=False, help_text='True while a session is active for this user.'),
        ),
    ]
