# Generated by Django 6.0.2 on 2026-04-01 19:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0007_userprofile_active_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allrequiredpayments',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code e.g. USD, GBP, EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='academic_course',
            field=models.ForeignKey(blank=True, help_text='The academic course unit this LMS content delivers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='eduweb.course'),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='certificate_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged to the student to receive their certificate', max_digits=10),
        ),
        migrations.AddField(
            model_name='staffpayroll',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code e.g. USD, GBP, EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('grade', 'Grade'), ('announcement', 'Announcement'), ('message', 'Message'), ('certificate', 'Certificate'), ('payroll', 'Payroll'), ('account', 'Account'), ('system', 'System')], max_length=30),
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=2)),
                ('credit_units', models.IntegerField(default=3)),
                ('is_passed', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='eduweb.courseapplication')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='eduweb.course')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='eduweb.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Grade',
                'verbose_name_plural': 'Course Grades',
                'ordering': ['session', 'course__year_of_study', 'course__semester'],
                'unique_together': {('student', 'course', 'session')},
            },
        ),
    ]
