# Generated by Django 6.0.2 on 2026-04-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0010_exam_examquestion_examstatuslog_studentexamresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='eduweb.academicsession'),
        ),
    ]
