# Generated by Django 6.0.2 on 2026-04-10 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0011_alter_exam_academic_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam_course_session_type',
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Academic course this exam belongs to. Null for standalone LMS-only exams.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='eduweb.course'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'academic_session', 'exam_type'), name='unique_exam_course_session_type'),
        ),
    ]
