# Generated by Django 6.0.2 on 2026-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0012_remove_exam_unique_exam_course_session_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmscourse',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Estimated duration in hours', max_digits=5),
        ),
    ]
