# Generated by Django 6.0.2 on 2026-04-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0013_alter_lmscourse_code_alter_lmscourse_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmscourse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='eduweb.coursecategory'),
        ),
    ]
