# Generated by Django 6.0.2 on 2026-04-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0014_alter_lmscourse_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(default=1, help_text='LMS course this exam belongs to. This may optionally be linked to an academic course via LMSCourse.', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='eduweb.lmscourse'),
            preserve_default=False,
        ),
    ]
