# Generated by Django 6.0.2 on 2026-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0015_alter_exam_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='visible_from',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='visible_until',
        ),
        migrations.AddField(
            model_name='exam',
            name='visible_from_override',
            field=models.DateTimeField(blank=True, help_text='Optional. Override when students can first see this exam. Leave blank to default to exam_start_datetime.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='visible_until_override',
            field=models.DateTimeField(blank=True, help_text='Optional. Override when this exam disappears from student view. Leave blank to default to exam_end_datetime.', null=True),
        ),
    ]
