# Generated by Django 6.0.2 on 2026-04-13 12:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0016_remove_exam_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='e.g. first, second, fall', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Course Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='eduweb_cour_academi_789293_idx',
        ),
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='first_semester_end',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='first_semester_start',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='second_semester_end',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='second_semester_start',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='override_current_term',
            field=models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester / Harmattan'), ('annual', 'Annual'), ('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], help_text='Admin override: force the system to report this term as current', max_length=20),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='term_dates',
            field=models.JSONField(default=list, help_text='List of term windows. Each item: {"term": "first|second|third|fall|spring|summer", "start": "YYYY-MM-DD", "end": "YYYY-MM-DD"}'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be passed before registering for this one', related_name='prerequisite_for', to='eduweb.course'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='lms_course',
            field=models.ForeignKey(blank=True, help_text='The LMS delivery this result is linked to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grades', to='eduweb.lmscourse'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='result_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('withheld', 'Withheld')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='term',
            field=models.CharField(blank=True, help_text='Term this grade belongs to', max_length=20),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Assigned academic lecturer for this delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses_as_lecturer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Academic session this delivery runs in. Null = self-paced standalone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='term',
            field=models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester'), ('annual', 'Annual'), ('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], help_text='Term within the session. Auto-derived from session.get_current_term() if blank.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admission_session',
            field=models.ForeignKey(blank=True, help_text='Session in which the student was admitted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progression_status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('repeated', 'Repeating Level'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current year of study. Level = year × 100 (e.g. year 1 = 100L).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='allrequiredpayments',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester'), ('annual', 'Annual'), ('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('access', 'Access'), ('export', 'Export'), ('permission_change', 'Permission Change'), ('course_access', 'Course Access'), ('assignment_submit', 'Assignment Submitted'), ('exam_start', 'Exam Started'), ('exam_finish', 'Exam Finished'), ('level_progression', 'Level Progression'), ('registration', 'Course Registration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='year_of_study',
            field=models.IntegerField(help_text='Which year of the program this course is taught in (e.g., 1, 2, 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='academic_course',
            field=models.ForeignKey(blank=True, help_text='The academic course unit this LMS content delivers. Null = standalone LMS course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='eduweb.course'),
        ),
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together={('student', 'course', 'session', 'term')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', '-timestamp'], name='eduweb_audi_user_id_385882_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type', 'year_of_study'], name='eduweb_cour_course__493bef_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['student', 'session'], name='eduweb_cour_student_f3fe8b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['result_status'], name='eduweb_cour_result__aa1e44_idx'),
        ),
        migrations.AddIndex(
            model_name='lmscourse',
            index=models.Index(fields=['session', 'term'], name='eduweb_lmsc_session_b430fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lmscourse',
            index=models.Index(fields=['academic_course', 'session'], name='eduweb_lmsc_academi_75e919_idx'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eduweb.course'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.AddIndex(
            model_name='courseregistration',
            index=models.Index(fields=['student', 'session', 'term'], name='eduweb_cour_student_3e4b15_idx'),
        ),
        migrations.AddIndex(
            model_name='courseregistration',
            index=models.Index(fields=['course', 'session'], name='eduweb_cour_course__42e35a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('student', 'course', 'session', 'term')},
        ),
    ]
