# Generated by Django 6.0.2 on 2026-04-13 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0017_courseregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_credits_per_semester',
            field=models.PositiveIntegerField(default=24, help_text='Maximum total credit units a student can register in ONE semester for this program', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
