# Generated by Django 6.0.2 on 2026-04-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0018_program_max_credits_per_semester'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lmscourse',
            name='eduweb_lmsc_categor_0b0e1d_idx',
        ),
    ]
