# Generated by Django 6.0.2 on 2026-04-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0019_remove_lmscourse_eduweb_lmsc_categor_0b0e1d_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmscourse',
            name='category',
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='difficulty_level',
            field=models.CharField(choices=[('1', '100 Level'), ('2', '200 Level'), ('3', '300 Level'), ('4', '400 Level'), ('5', '500 Level'), ('6', '600 Level'), ('7', '700 Level'), ('8', '800 Level')], default='1', max_length=5, verbose_name='Level'),
        ),
    ]
