# Generated by Django 6.0.2 on 2026-04-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0020_remove_lmscourse_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseapplication',
            name='intake',
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='entry_level',
            field=models.IntegerField(blank=True, help_text='Entry level e.g. 100, 200, 300 etc.', null=True),
        ),
    ]
