# Generated by Django 6.0.3 on 2026-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0021_remove_courseapplication_intake_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['year_of_study', 'semester', 'name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='allrequiredpayments',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='color_primary',
        ),
        migrations.RemoveField(
            model_name='course',
            name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='course',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.AddField(
            model_name='allrequiredpayments',
            name='level',
            field=models.IntegerField(blank=True, choices=[(100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400'), (500, 'Level 500'), (600, 'Level 600'), (700, 'Level 700'), (800, 'Level 800')], help_text='Student level this fee applies to (100–800). Leave blank to apply to ALL levels.', null=True),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='difficulty_level',
            field=models.IntegerField(choices=[(100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400'), (500, 'Level 500'), (600, 'Level 600'), (700, 'Level 700'), (800, 'Level 800')], default=100, verbose_name='Level'),
        ),
        migrations.AlterUniqueTogether(
            name='allrequiredpayments',
            unique_together={('program', 'academic_session', 'purpose', 'semester', 'level')},
        ),
    ]
