# Generated by Django 6.0.2 on 2026-04-25 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import datetime
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0022_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.RemoveConstraint(
            model_name='exam',
            name='exam_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam_course_session_type',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='eduweb_exam_exam_da_f62253_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='eduweb_exam_academi_389c35_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='eduweb_exam_course__748b29_idx',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 10, 0, tzinfo=datetime.timezone.utc), help_text='Exam end (date + time). Server fires auto-submit at this moment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 1, 1, 8, 0, tzinfo=datetime.timezone.utc), help_text='Exact exam start (date + time). The instruction-page countdown counts to this.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(help_text='LMS course this exam belongs to. Academic session, department, and eligible student level are all derived from here — no need to store them separately.', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='eduweb.lmscourse'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated on save. e.g. EX-2025-4F2A.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='special_instructions',
            field=models.TextField(blank=True, help_text="Additional notes shown on the exam listing (e.g. 'Have your matric card ready')."),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_datetime', 'status'], name='eduweb_exam_start_d_7f6796_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'start_datetime'], name='eduweb_exam_course__746e4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(check=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='exam_end_after_start'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='accommodation_notes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='clash_group',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='department',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='difficulty_mix',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='eligible_levels',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='expected_candidates',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='hall_capacity',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='has_accommodations',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='has_clash',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='instruction_window_minutes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='invigilators',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='seating_plan_file',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='timetable_file',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='visible_from_override',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='visible_until_override',
        ),
    ]
