# Generated by Django 6.0.2 on 2026-04-27 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0023_alter_exam_options_remove_exam_exam_end_after_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['exam', 'created_at'], 'verbose_name': 'Exam Question', 'verbose_name_plural': 'Exam Questions'},
        ),
        migrations.RemoveIndex(
            model_name='examquestion',
            name='eduweb_exam_exam_id_47ece1_idx',
        ),
        migrations.RemoveIndex(
            model_name='examquestion',
            name='eduweb_exam_exam_id_ef097d_idx',
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'is_active'], name='eduweb_exam_exam_id_fea488_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'created_at'], name='eduweb_exam_exam_id_f9f459_idx'),
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='import_row_number',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='order',
        ),
    ]
