# Generated by Django 6.0.2 on 2026-04-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0024_alter_examquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmscourse',
            name='certificate_fee',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='certificate_template',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='enrollment_end_date',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='enrollment_start_date',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='has_certificate',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='instructor_bio',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='language',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='max_students',
        ),
    ]
