# Generated by Django 6.0.2 on 2026-04-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0025_remove_lmscourse_certificate_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsession',
            name='override_current_term',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='registration_start',
        ),
    ]
