# Generated by Django 6.0.2 on 2026-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0026_remove_academicsession_override_current_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Failed OTP attempts for current code. Locked after 5.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, default='', help_text='Current one-time password (6 digits).', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='When the OTP was last generated. Expires after 10 minutes.', null=True),
        ),
    ]
