# Generated by Django 6.0.2 on 2026-06-23 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0027_userprofile_otp_attempts_userprofile_otp_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_otp_code',
            field=models.CharField(blank=True, db_column='otp_code', default='', help_text='Encrypted one-time password (6 digits).', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='courseapplication',
            constraint=models.UniqueConstraint(fields=('email', 'program'), name='unique_application_email_per_program'),
        ),
    ]
