# Generated by Django 6.0.2 on 2026-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0028_remove_userprofile_otp_code_userprofile__otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If True, user is redirected to change password immediately after login.'),
        ),
    ]
