# Generated by Django 6.0.2 on 2026-06-24 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0029_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermissionsMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Administrator'), ('support', 'Support Staff'), ('finance', 'Finance Manager')], max_length=30, null=True)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('user_management', 'User Management'), ('academics', 'Academics'), ('lms_courses', 'LMS Courses'), ('applications', 'Applications'), ('exams', 'Exams'), ('enrollments', 'Enrollments'), ('finance', 'Finance'), ('communications', 'Communications'), ('blog', 'Blog'), ('library', 'Library'), ('site_content', 'Site Content'), ('security_audit', 'Security & Audit')], max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_matrix_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_matrix_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Permissions Matrix Row',
                'verbose_name_plural': 'Staff Permissions Matrix',
                'ordering': ['role', 'user', 'module'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user', None)), fields=('role', 'module'), name='unique_staff_role_module'), models.UniqueConstraint(condition=models.Q(('role', None)), fields=('user', 'module'), name='unique_staff_user_module'), models.CheckConstraint(check=models.Q(models.Q(('role__isnull', False), ('user__isnull', True)), models.Q(('role__isnull', True), ('user__isnull', False)), _connector='OR'), name='staff_matrix_role_xor_user')],
            },
        ),
    ]
