# Generated by Django 6.0.3 on 2026-07-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0030_staffpermissionsmatrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Lecturers'), ('admin', 'Admin'), ('support', 'Support'), ('finance', 'Finance')], default='student', max_length=30),
        ),
    ]
