# Generated by Django 6.0.2 on 2026-07-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0031_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpermissionsmatrix',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('user_management', 'User Management'), ('academics', 'Academics'), ('lms_courses', 'LMS Courses'), ('applications', 'Applications'), ('exams', 'Exams'), ('enrollments', 'Enrollments'), ('finance', 'Finance'), ('communications', 'Communications'), ('blog', 'Blog'), ('library', 'Library'), ('site_content', 'Site Content'), ('security_audit', 'Security & Audit'), ('instructor_courses', 'My Courses'), ('instructor_assessments', 'Assessments'), ('instructor_analytics', 'Analytics'), ('instructor_resources', 'Resources'), ('instructor_communications', 'Communications')], max_length=40),
        ),
        migrations.AlterField(
            model_name='staffpermissionsmatrix',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('support', 'Support Staff'), ('finance', 'Finance Manager'), ('instructor', 'Instructor')], max_length=30, null=True),
        ),
    ]
