# Generated by Django 6.0.2 on 2026-07-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0033_seed_instructor_role_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpermissionsmatrix',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('user_management', 'User Management'), ('academics', 'Academics'), ('lms_courses', 'LMS Courses'), ('applications', 'Applications'), ('exams', 'Exams'), ('enrollments', 'Enrollments'), ('finance', 'Finance'), ('communications', 'Communications'), ('blog', 'Blog'), ('library', 'Library'), ('site_content', 'Site Content'), ('security_audit', 'Security & Audit'), ('instructor_courses', 'My Courses'), ('instructor_assessments', 'Assessments'), ('instructor_analytics', 'Analytics'), ('instructor_resources', 'Resources'), ('instructor_communications', 'Communications'), ('finance_payments', 'Payments'), ('finance_subscriptions', 'Subscriptions'), ('finance_payroll', 'Payroll')], max_length=40),
        ),
    ]
