# Generated by Django 6.0.2 on 2026-07-13 11:52

import django.core.validators
import django.db.models.deletion
import apps.eduweb.models as eduweb_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0037_seed_support_portal_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='min_cgpa_to_progress',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum cumulative GPA (5-point scale) required to advance to the next year of study', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='staffpermissionsmatrix',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('user_management', 'User Management'), ('academics', 'Academics'), ('lms_courses', 'LMS Courses'), ('applications', 'Applications'), ('exams', 'Exams'), ('enrollments', 'Enrollments'), ('finance', 'Finance'), ('communications', 'Communications'), ('blog', 'Blog'), ('library', 'Library'), ('site_content', 'Site Content'), ('security_audit', 'Security & Audit'), ('instructor_courses', 'My Courses'), ('instructor_assessments', 'Assessments'), ('instructor_analytics', 'Analytics'), ('instructor_resources', 'Resources'), ('instructor_communications', 'Communications'), ('finance_payments', 'Payments'), ('finance_subscriptions', 'Subscriptions'), ('finance_payroll', 'Payroll'), ('support_tickets', 'Tickets'), ('support_knowledge_base', 'Knowledge Base'), ('support_communications', 'Communications'), ('support_analytics', 'Analytics'), ('support_config', 'Support Config'), ('academic_progression', 'Academic Progression')], max_length=40),
        ),
        migrations.CreateModel(
            name='CourseCarryOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_failed_term', models.CharField(blank=True, max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=1, help_text='Number of times this course has been attempted and failed.')),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_session', models.ForeignKey(blank=True, help_text='Session in which a passing grade finally cleared this carry-over.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eduweb.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_over_records', to='eduweb.course')),
                ('first_failed_session', models.ForeignKey(help_text='Session in which this course was first failed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eduweb.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_overs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Carry-Over',
                'verbose_name_plural': 'Course Carry-Overs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'is_cleared'], name='eduweb_cour_student_38e8b1_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('previous_year_of_study', models.PositiveSmallIntegerField()),
                ('new_year_of_study', models.PositiveSmallIntegerField()),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('core_courses_passed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, help_text='Carried-over courses, attempt counts, and other decision context.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_decisions_made', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_logs', to='eduweb.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Decision Log',
                'verbose_name_plural': 'Progression Decision Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'session'], name='eduweb_prog_student_6ec391_idx')],
            },
            bases=(eduweb_models.ImmutableMixin, models.Model),
        ),
    ]
