# Generated by Django 6.0.2 on 2026-07-13 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0039_seed_academic_progression_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignment_weight_pct',
            field=models.PositiveSmallIntegerField(default=15, help_text='Weight of assignment scores in the final course grade (%)', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_weight_pct',
            field=models.PositiveSmallIntegerField(default=70, help_text='Weight of the end-of-semester exam in the final course grade (%)', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_weight_pct',
            field=models.PositiveSmallIntegerField(default=15, help_text='Weight of quiz scores in the final course grade (%)', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
