# Generated by Django 6.0.2 on 2026-07-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0040_course_assessment_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='registration_override',
            field=models.CharField(choices=[('auto', 'Automatic (3-week window from term start)'), ('open', 'Force Open'), ('closed', 'Force Closed')], default='auto', help_text="Overrides the automatic 3-week registration window. Use 'Force Open' when a session is activated after its term's computed window has already elapsed (e.g. after end-of-session progression runs late).", max_length=10),
        ),
    ]
