# Generated by Django 6.0.2 on 2026-07-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0041_academicsession_registration_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='pending_manual_grading',
            field=models.BooleanField(default=False, help_text="True while this attempt has short-answer/essay responses an instructor hasn't graded yet."),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_responses_graded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='needs_grading',
            field=models.BooleanField(default=False, help_text="True for short-answer/essay responses awaiting an instructor's manual score."),
        ),
    ]
