# Generated by Django 6.0.2 on 2026-07-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0042_quizattempt_pending_manual_grading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='intake',
            field=models.ForeignKey(blank=True, help_text='Which intake period this application is for, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='eduweb.courseintake'),
        ),
    ]
