# Generated by Django 6.0.2 on 2026-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0044_seed_admin_finance_payroll_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
