# Generated by Django 6.0.2 on 2026-07-14 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0045_broadcastmessage_sending_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpayroll',
            name='staff',
            field=models.ForeignKey(help_text='Select staff member (non-students only)', limit_choices_to={'profile__role__in': ['instructor', 'support', 'admin', 'finance']}, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL),
        ),
    ]
