# Generated by Django 6.0.2 on 2026-07-14 09:38

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0046_alter_staffpayroll_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='transcript_issued_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who issued this transcript', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='transcript_snapshot',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Frozen copy of the student's grade record, captured the moment transcript_requested is set. Once requested, the transcript view renders this locked snapshot instead of live CourseGrade data, so results recorded afterwards can't silently change an already-requested transcript.", null=True),
        ),
    ]
