# Generated by Django 6.0.2 on 2026-07-14 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0048_seed_admin_finance_payments_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
