# Generated by Django 5.0.1 on 2026-07-21 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0054_alter_staffpermissionsmatrix_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='credit_caps_by_term',
            field=models.JSONField(blank=True, default=dict, help_text="Optional per-term overrides, e.g. {'first': 21, 'second': 18}. A term key not present here falls back to max_credits_per_semester. Use max_credits_for_term(term) rather than reading either field directly."),
        ),
        migrations.AlterField(
            model_name='program',
            name='max_credits_per_semester',
            field=models.PositiveIntegerField(default=24, help_text='Default maximum credit units per term — used for any term not overridden in credit_caps_by_term below.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
