# Generated by Django 5.0.1 on 2026-07-22 02:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0055_program_credit_caps_by_term_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSessionCreditCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text="Term key matching one of this session's term_dates entries (e.g. 'first', 'second', 'third').", max_length=20)),
                ('max_credit_units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_credit_caps', to='eduweb.program')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_credit_caps', to='eduweb.academicsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program Session Credit Cap',
                'verbose_name_plural': 'Program Session Credit Caps',
                'ordering': ['session__name', 'term'],
                'unique_together': {('program', 'session', 'term')},
            },
        ),
    ]
