# Generated by Django 5.0.1 on 2026-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0056_programsessioncreditcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpermissionsmatrix',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('user_management', 'User Management'), ('academics', 'Academics'), ('lms_courses', 'LMS Courses'), ('applications', 'Applications'), ('exams', 'Exams'), ('enrollments', 'Enrollments'), ('finance', 'Finance'), ('communications', 'Communications'), ('blog', 'Blog'), ('library', 'Library'), ('site_content', 'Site Content'), ('security_audit', 'Security & Audit'), ('instructor_courses', 'My Courses'), ('instructor_assessments', 'Assessments'), ('instructor_analytics', 'Analytics'), ('instructor_resources', 'Resources'), ('instructor_communications', 'Communications'), ('finance_payments', 'Payments'), ('finance_subscriptions', 'Subscriptions'), ('finance_payroll', 'Payroll'), ('support_tickets', 'Tickets'), ('support_knowledge_base', 'Knowledge Base'), ('support_communications', 'Communications'), ('support_analytics', 'Analytics'), ('support_config', 'Support Config'), ('academic_progression', 'Academic Progression'), ('results_publish', 'Results Publishing'), ('role_permissions', 'Roles & Permissions')], max_length=40),
        ),
    ]
