# Generated by Django 5.0.1 on 2026-07-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0057_alter_staffpermissionsmatrix_module'),
        ('eduweb', '0057_faculty_gallery_program_gallery'),
    ]

    operations = [
    ]
