# Generated by Django 5.0.1 on 2026-07-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0058_merge_20260725_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['created_at'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='display_order',
        ),
    ]
