# Generated by Django 5.0.1 on 2026-07-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0059_remove_program_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='avg_starting_salary',
        ),
        migrations.RemoveField(
            model_name='program',
            name='job_placement_rate',
        ),
    ]
