# Generated by Django 5.0.1 on 2026-07-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0060_remove_program_marketing_stat_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='application_fee',
        ),
        migrations.AddField(
            model_name='courseintake',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee to apply for this specific intake', max_digits=10),
        ),
        migrations.AddField(
            model_name='courseintake',
            name='application_start_date',
            field=models.DateField(blank=True, help_text='When applications open for this intake', null=True),
        ),
        migrations.AlterField(
            model_name='courseintake',
            name='application_deadline',
            field=models.DateField(help_text='Application closing date for this intake'),
        ),
        migrations.AlterField(
            model_name='courseintake',
            name='start_date',
            field=models.DateField(help_text='Program start date for this intake'),
        ),
    ]
