# Generated by Django 5.0.1 on 2026-07-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0061_remove_program_application_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['name'], 'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='institutionmember',
            options={'ordering': ['name'], 'verbose_name': 'Institution Member', 'verbose_name_plural': 'Institution Members'},
        ),
        migrations.AlterModelOptions(
            name='institutionpartner',
            options={'ordering': ['name'], 'verbose_name': 'Institution Partner / Affiliation', 'verbose_name_plural': 'Institution Partners & Affiliations'},
        ),
        migrations.AlterModelOptions(
            name='sitehistorymilestone',
            options={'ordering': ['year'], 'verbose_name': 'History Milestone', 'verbose_name_plural': 'History Milestones'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='department',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='institutionmember',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='institutionpartner',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='sitehistorymilestone',
            name='display_order',
        ),
    ]
