# Generated by Django 5.0.1 on 2026-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0062_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmscourse',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
