# Generated by Django 5.0.1 on 2026-07-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0063_alter_lmscourse_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['author_name'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='order',
        ),
    ]
