# Generated by Django 5.0.1 on 2026-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0064_alter_testimonial_options_remove_testimonial_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='study_mode',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Online', 'Online'), ('Blended', 'Blended')], max_length=20),
        ),
    ]
