# Generated by Django 5.0.1 on 2026-08-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0065_fix_study_mode_choices_casing'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionmember',
            name='is_who_we_are',
            field=models.BooleanField(default=False, help_text='Featured on the About page "Who We Are" section. Only one member may be featured at a time.', verbose_name='Show in "Who We Are"'),
        ),
    ]
