"""
Django settings for DigitalCampus project.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
from decouple import Config, RepositoryEnv
import os

# --------------------------------------------------
# BASE DIR & ENV
# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / ".env"
config = Config(RepositoryEnv(env_path))

# --------------------------------------------------
# SECURITY
# --------------------------------------------------

# FIX: SECRET_KEY must use its own key, NOT STRIPE_SECRET_KEY
SECRET_KEY = config("SECRET_KEY", default="django-insecure-change-this-in-production")

DEBUG = config("DEBUG", default=True, cast=bool)

# FIX: Hardcoded ALLOWED_HOSTS — no https://, no spaces issues, no .env parsing problems
ALLOWED_HOSTS = [
    "miuedu.com",
    "www.miuedu.com",
    "127.0.0.1",
    "localhost",
    "https://www.miuedu.com",
    "mail.miuedu.com",
]

# --------------------------------------------------
# APPLICATION DEFINITION
# --------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "DigitalCampus",

    # Project apps
    "eduweb",
    "management",
    "student",
    "parent",
    "instructor",
    "finance",
    "payment",
    "melbac",
    'library',

    "django.contrib.humanize",
    'chatbot',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "eduweb.security_middleware.SessionSecurityMiddleware",
    "eduweb.exam_middleware.ExamLockMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

ROOT_URLCONF = "DigitalCampus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "eduweb.views.application_status_context",
                "eduweb.context.navigation_data",
                'eduweb.context.site_config_context',
                "eduweb.context.student_counts",
                'eduweb.context.admin_counts',
            ],
        },
    },
]

WSGI_APPLICATION = "DigitalCampus.wsgi.application"

# --------------------------------------------------
# DATABASE
# --------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------

LANGUAGE_CODE = "en-ng"
TIME_ZONE = "Africa/Lagos"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# STATIC & MEDIA
# --------------------------------------------------

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
FILE_UPLOAD_PERMISSIONS = 0o644

# --------------------------------------------------
# DEFAULT PRIMARY KEY
# --------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------------------------------------
# EMAIL CONFIGURATION
# --------------------------------------------------

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="MIU <noreply@miu.edu>")
CONTACT_EMAIL = config("CONTACT_EMAIL", default="admin@miu.edu")

# --------------------------------------------------
# AUTH & SESSION
# --------------------------------------------------

LOGIN_URL = "/auth/"
LOGIN_REDIRECT_URL = "eduweb:apply"
LOGOUT_REDIRECT_URL = "eduweb:index"

SESSION_COOKIE_AGE = 1209600
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # per-login set_expiry(0) handles browser-close
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

SESSION_ENGINE = "django.contrib.sessions.backends.db"
CSRF_COOKIE_HTTPONLY = False

# --------------------------------------------------
# SECURITY FLAGS (PRODUCTION)
# --------------------------------------------------

SECURE_SSL_REDIRECT = config(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=False,
    cast=bool,
)

CSRF_COOKIE_SECURE = config(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=False,
    cast=bool,
)

# --------------------------------------------------
# STRIPE PAYMENT SETTINGS
# --------------------------------------------------

STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLIC_KEY = config("STRIPE_PUBLIC_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

# --------------------------------------------------
# CORS / CSRF
# --------------------------------------------------

# FIX: Hardcoded trusted origins with proper https:// format
CSRF_TRUSTED_ORIGINS = [
    "https://miuedu.com",
    "https://www.miuedu.com",
    "http://127.0.0.1",
    "http://localhost",
]

CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS

# settings.py
CHAT_SESSION_TIMEOUT_MINUTES = 15

# ── Inactivity session timeout ────────────────────────────────────────────────
# Minutes of no requests before SessionSecurityMiddleware kills the session.
# Change this single value to adjust the timeout across the whole platform.
SESSION_INACTIVITY_TIMEOUT = 15  # minutes